name: Linux

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release
  QT_VERSION: "6.4.3"
  QT_ARCH: "gcc_64"

jobs:
  build:
    # Qt 6.3 requires Ubuntu 20.04
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{runner.workspace}}/Qt
          key: qt-${{env.QT_VERSION}}-${{env.QT_ARCH}}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{steps.cache-qt.outputs.cache-hit}}
          version: ${{env.QT_VERSION}}
          arch: ${{env.QT_ARCH}}

      - name: Configure CMake
        run: cmake . -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/usr -DUSE_TESTS=ON -DUSE_LTO=ON

      - name: Build
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        run: ${{runner.workspace}}/spotify-qt/lib/test/spotify-qt-lib-test

      - name: Install
        run: make DESTDIR="${{runner.workspace}}/dist" install

      - name: Download linuxdeploy
        run: |
          curl -L "https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage" -o ${{runner.workspace}}/linuxdeploy-x86_64.AppImage
          curl -L "https://github.com/linuxdeploy/linuxdeploy-plugin-appimage/releases/download/continuous/linuxdeploy-plugin-appimage-x86_64.AppImage" -o ${{runner.workspace}}/linuxdeploy-plugin-appimage-x86_64.AppImage
          curl -L "https://github.com/linuxdeploy/linuxdeploy-plugin-qt/releases/download/continuous/linuxdeploy-plugin-qt-x86_64.AppImage" -o ${{runner.workspace}}/linuxdeploy-plugin-qt-x86_64.AppImage
          chmod +x ${{runner.workspace}}/linuxdeploy-*.AppImage

      - name: Copy OpenSSL
        run: |
          mkdir -p ${{runner.workspace}}/dist/usr/lib
          cp /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 ${{runner.workspace}}/dist/usr/lib/
          cp /usr/lib/x86_64-linux-gnu/libssl.so.1.1 ${{runner.workspace}}/dist/usr/lib/

      - name: Package
        run: |
          export OUTPUT="spotify-qt-$(git rev-parse --short HEAD)-x86_64.AppImage"
          ${{runner.workspace}}/linuxdeploy-x86_64.AppImage --appdir ${{runner.workspace}}/dist --output appimage --plugin qt -d ${{runner.workspace}}/dist/usr/share/applications/spotify-qt.desktop

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: spotify-qt
          path: ${{runner.workspace}}/spotify-qt/spotify-qt-*.AppImage
