name: Windows (Qt 6, x64)

on: [ push, pull_request ]

env:
  BUILD_TYPE: Release
  QT_VERSION: "6.3.0"
  QT_ARCH: "win64_msvc2019_64"
  CMAKE_GENERATOR: "Visual Studio 17 2022"
  CMAKE_ARCH: "x64"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ${{runner.workspace}}/Qt
          key: qt-${{env.QT_VERSION}}-${{env.QT_ARCH}}

      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          cached: ${{steps.cache-qt.outputs.cache-hit}}
          version: ${{env.QT_VERSION}}
          arch: ${{env.QT_ARCH}}

      - name: Configure CMake
        run: cmake . -G "${{env.CMAKE_GENERATOR}}" -A ${{env.CMAKE_ARCH}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DUSE_TESTS=ON

      - name: Build
        run: cmake --build . --config ${{env.BUILD_TYPE}}

      - name: Test
        run: ${{runner.workspace}}/spotify-qt/lib/test/${{env.BUILD_TYPE}}/spotify-qt-lib-test.exe

      - name: Package
        run: windeployqt --no-opengl-sw ${{runner.workspace}}/spotify-qt/${{env.BUILD_TYPE}}/spotify-qt.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: spotify-qt
          path: ${{runner.workspace}}/spotify-qt/${{env.BUILD_TYPE}}
